(base) harshithansraj@Harshits-MacBook-Air django-setup % pip3 install django
Defaulting to user installation because normal site-packages is not writeable
Collecting django
  Downloading Django-4.2.11-py3-none-any.whl.metadata (4.2 kB)
Collecting asgiref<4,>=3.6.0 (from django)
  Downloading asgiref-3.8.0-py3-none-any.whl.metadata (9.3 kB)
Collecting sqlparse>=0.3.1 (from django)
  Downloading sqlparse-0.4.4-py3-none-any.whl.metadata (4.0 kB)
Collecting typing-extensions>=4 (from asgiref<4,>=3.6.0->django)
  Downloading typing_extensions-4.10.0-py3-none-any.whl.metadata (3.0 kB)
Downloading Django-4.2.11-py3-none-any.whl (8.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.0/8.0 MB 2.0 MB/s eta 0:00:00
Downloading asgiref-3.8.0-py3-none-any.whl (23 kB)
Downloading sqlparse-0.4.4-py3-none-any.whl (41 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.2/41.2 kB 3.3 MB/s eta 0:00:00
Downloading typing_extensions-4.10.0-py3-none-any.whl (33 kB)
Installing collected packages: typing-extensions, sqlparse, asgiref, django
  WARNING: The script sqlformat is installed in '/Users/harshithansraj/Library/Python/3.9/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  NOTE: The current PATH contains path(s) starting with `~`, which may not be expanded by all applications.
  WARNING: The script django-admin is installed in '/Users/harshithansraj/Library/Python/3.9/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  NOTE: The current PATH contains path(s) starting with `~`, which may not be expanded by all applications.
Successfully installed asgiref-3.8.0 django-4.2.11 sqlparse-0.4.4 typing-extensions-4.10.0
(base) harshithansraj@Harshits-MacBook-Air django-setup % django-admin startproject demo
(base) harshithansraj@Harshits-MacBook-Air django-setup % cd demo
(base) harshithansraj@Harshits-MacBook-Air demo % python manage.py startapp myapp
(base) harshithansraj@Harshits-MacBook-Air demo % python manage.py runserver
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).

You have 18 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.
Run 'python manage.py migrate' to apply them.
March 21, 2024 - 14:12:32
Django version 4.2.10, using settings 'demo.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.

Not Found: /
[21/Mar/2024 14:12:44] "GET / HTTP/1.1" 404 2163
Not Found: /favicon.ico
[21/Mar/2024 14:12:45] "GET /favicon.ico HTTP/1.1" 404 2214
/Users/harshithansraj/Desktop/IT project/django-setup/demo/demo/urls.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).

You have 18 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.
Run 'python manage.py migrate' to apply them.
March 21, 2024 - 14:16:21
Django version 4.2.10, using settings 'demo.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.

[21/Mar/2024 14:16:27] "GET / HTTP/1.1" 200 12
/Users/harshithansraj/Desktop/IT project/django-setup/demo/myapp/views.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).

You have 18 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.
Run 'python manage.py migrate' to apply them.
March 21, 2024 - 14:21:56
Django version 4.2.10, using settings 'demo.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.

Internal Server Error: /
Traceback (most recent call last):
  File "/Users/harshithansraj/opt/anaconda3/lib/python3.9/site-packages/django/template/base.py", line 505, in parse
    compile_func = self.tags[command]
KeyError: 'endblock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/harshithansraj/opt/anaconda3/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/harshithansraj/opt/anaconda3/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/harshithansraj/Desktop/IT project/django-setup/demo/myapp/views.py", line 3, in home
    return render(request,"home.html")
  File "/Users/harshithansraj/opt/anaconda3/lib/python3.9/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/harshithansraj/opt/anaconda3/lib/python3.9/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/harshithansraj/opt/anaconda3/lib/python3.9/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/Users/harshithansraj/opt/anaconda3/lib/python3.9/site-packages/django/template/backends/django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/Users/harshithansraj/opt/anaconda3/lib/python3.9/site-packages/django/template/engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "/Users/harshithansraj/opt/anaconda3/lib/python3.9/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "/Users/harshithansraj/opt/anaconda3/lib/python3.9/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/Users/harshithansraj/opt/anaconda3/lib/python3.9/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/Users/harshithansraj/opt/anaconda3/lib/python3.9/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/Users/harshithansraj/opt/anaconda3/lib/python3.9/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
  File "/Users/harshithansraj/opt/anaconda3/lib/python3.9/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/Users/harshithansraj/opt/anaconda3/lib/python3.9/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/Users/harshithansraj/opt/anaconda3/lib/python3.9/site-packages/django/template/loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
  File "/Users/harshithansraj/opt/anaconda3/lib/python3.9/site-packages/django/template/base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/Users/harshithansraj/opt/anaconda3/lib/python3.9/site-packages/django/template/base.py", line 568, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 4: 'endblock'. Did you forget to register or load this tag?
[21/Mar/2024 14:22:01] "GET / HTTP/1.1" 500 139567
[21/Mar/2024 14:23:34] "GET / HTTP/1.1" 200 1390
/Users/harshithansraj/Desktop/IT project/django-setup/demo/myapp/models.py changed, reloading.
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/Users/harshithansraj/opt/anaconda3/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/Users/harshithansraj/opt/anaconda3/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/harshithansraj/opt/anaconda3/lib/python3.9/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/Users/harshithansraj/opt/anaconda3/lib/python3.9/site-packages/django/core/management/commands/runserver.py", line 125, in inner_run
    autoreload.raise_last_exception()
  File "/Users/harshithansraj/opt/anaconda3/lib/python3.9/site-packages/django/utils/autoreload.py", line 87, in raise_last_exception
    raise _exception[1]
  File "/Users/harshithansraj/opt/anaconda3/lib/python3.9/site-packages/django/core/management/__init__.py", line 394, in execute
    autoreload.check_errors(django.setup)()
  File "/Users/harshithansraj/opt/anaconda3/lib/python3.9/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/Users/harshithansraj/opt/anaconda3/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/harshithansraj/opt/anaconda3/lib/python3.9/site-packages/django/apps/registry.py", line 116, in populate
    app_config.import_models()
  File "/Users/harshithansraj/opt/anaconda3/lib/python3.9/site-packages/django/apps/config.py", line 269, in import_models
    self.models_module = import_module(models_module_name)
  File "/Users/harshithansraj/opt/anaconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/harshithansraj/Desktop/IT project/django-setup/demo/myapp/models.py", line 6
    title = models.CharField(max_length=200)
    ^
IndentationError: expected an indented block
/Users/harshithansraj/Desktop/IT project/django-setup/demo/myapp/models.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).

You have 18 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.
Run 'python manage.py migrate' to apply them.
March 21, 2024 - 14:24:52
Django version 4.2.10, using settings 'demo.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.

/Users/harshithansraj/Desktop/IT project/django-setup/demo/myapp/admin.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).

You have 18 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.
Run 'python manage.py migrate' to apply them.
March 21, 2024 - 14:25:15
Django version 4.2.10, using settings 'demo.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.

/Users/harshithansraj/Desktop/IT project/django-setup/demo/myapp/admin.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).

You have 18 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.
Run 'python manage.py migrate' to apply them.
March 21, 2024 - 14:25:26
Django version 4.2.10, using settings 'demo.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.

^C%                                                                                                                                                                     
(base) harshithansraj@Harshits-MacBook-Air demo % python manage.py makemigrations
Migrations for 'myapp':
  myapp/migrations/0001_initial.py
    - Create model TodoItem
(base) harshithansraj@Harshits-MacBook-Air demo % python manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, myapp, sessions
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying admin.0003_logentry_add_action_flag_choices... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying auth.0010_alter_group_name_max_length... OK
  Applying auth.0011_update_proxy_permissions... OK
  Applying auth.0012_alter_user_first_name_max_length... OK
  Applying myapp.0001_initial... OK
  Applying sessions.0001_initial... OK
(base) harshithansraj@Harshits-MacBook-Air demo % python manage.py runserver
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
March 21, 2024 - 14:26:37
Django version 4.2.10, using settings 'demo.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.

/Users/harshithansraj/Desktop/IT project/django-setup/demo/myapp/views.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/Users/harshithansraj/opt/anaconda3/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/Users/harshithansraj/opt/anaconda3/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/harshithansraj/opt/anaconda3/lib/python3.9/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/Users/harshithansraj/opt/anaconda3/lib/python3.9/site-packages/django/core/management/commands/runserver.py", line 133, in inner_run
    self.check(display_num_errors=True)
  File "/Users/harshithansraj/opt/anaconda3/lib/python3.9/site-packages/django/core/management/base.py", line 485, in check
    all_issues = checks.run_checks(
  File "/Users/harshithansraj/opt/anaconda3/lib/python3.9/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/Users/harshithansraj/opt/anaconda3/lib/python3.9/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/Users/harshithansraj/opt/anaconda3/lib/python3.9/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    return check_method()
  File "/Users/harshithansraj/opt/anaconda3/lib/python3.9/site-packages/django/urls/resolvers.py", line 494, in check
    for pattern in self.url_patterns:
  File "/Users/harshithansraj/opt/anaconda3/lib/python3.9/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/harshithansraj/opt/anaconda3/lib/python3.9/site-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Users/harshithansraj/opt/anaconda3/lib/python3.9/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/harshithansraj/opt/anaconda3/lib/python3.9/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
  File "/Users/harshithansraj/opt/anaconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/harshithansraj/Desktop/IT project/django-setup/demo/demo/urls.py", line 22, in <module>
    path("",include("myapp.urls"))
  File "/Users/harshithansraj/opt/anaconda3/lib/python3.9/site-packages/django/urls/conf.py", line 38, in include
    urlconf_module = import_module(urlconf_module)
  File "/Users/harshithansraj/opt/anaconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/harshithansraj/Desktop/IT project/django-setup/demo/myapp/urls.py", line 2, in <module>
    from . import views
  File "/Users/harshithansraj/Desktop/IT project/django-setup/demo/myapp/views.py", line 6
    return render(request,"todos.html",{"todos":})
                                                ^
SyntaxError: invalid syntax
/Users/harshithansraj/Desktop/IT project/django-setup/demo/myapp/views.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/Users/harshithansraj/opt/anaconda3/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/Users/harshithansraj/opt/anaconda3/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/harshithansraj/opt/anaconda3/lib/python3.9/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/Users/harshithansraj/opt/anaconda3/lib/python3.9/site-packages/django/core/management/commands/runserver.py", line 133, in inner_run
    self.check(display_num_errors=True)
  File "/Users/harshithansraj/opt/anaconda3/lib/python3.9/site-packages/django/core/management/base.py", line 485, in check
    all_issues = checks.run_checks(
  File "/Users/harshithansraj/opt/anaconda3/lib/python3.9/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/Users/harshithansraj/opt/anaconda3/lib/python3.9/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/Users/harshithansraj/opt/anaconda3/lib/python3.9/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    return check_method()
  File "/Users/harshithansraj/opt/anaconda3/lib/python3.9/site-packages/django/urls/resolvers.py", line 494, in check
    for pattern in self.url_patterns:
  File "/Users/harshithansraj/opt/anaconda3/lib/python3.9/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/harshithansraj/opt/anaconda3/lib/python3.9/site-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Users/harshithansraj/opt/anaconda3/lib/python3.9/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/harshithansraj/opt/anaconda3/lib/python3.9/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
  File "/Users/harshithansraj/opt/anaconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/harshithansraj/Desktop/IT project/django-setup/demo/demo/urls.py", line 22, in <module>
    path("",include("myapp.urls"))
  File "/Users/harshithansraj/opt/anaconda3/lib/python3.9/site-packages/django/urls/conf.py", line 38, in include
    urlconf_module = import_module(urlconf_module)
  File "/Users/harshithansraj/opt/anaconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/harshithansraj/Desktop/IT project/django-setup/demo/myapp/urls.py", line 2, in <module>
    from . import views
  File "/Users/harshithansraj/Desktop/IT project/django-setup/demo/myapp/views.py", line 7
    return render(request,"todos.html",{"todos":})
                                                ^
SyntaxError: invalid syntax
/Users/harshithansraj/Desktop/IT project/django-setup/demo/myapp/views.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/Users/harshithansraj/opt/anaconda3/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/Users/harshithansraj/opt/anaconda3/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/harshithansraj/opt/anaconda3/lib/python3.9/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/Users/harshithansraj/opt/anaconda3/lib/python3.9/site-packages/django/core/management/commands/runserver.py", line 133, in inner_run
    self.check(display_num_errors=True)
  File "/Users/harshithansraj/opt/anaconda3/lib/python3.9/site-packages/django/core/management/base.py", line 485, in check
    all_issues = checks.run_checks(
  File "/Users/harshithansraj/opt/anaconda3/lib/python3.9/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/Users/harshithansraj/opt/anaconda3/lib/python3.9/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/Users/harshithansraj/opt/anaconda3/lib/python3.9/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    return check_method()
  File "/Users/harshithansraj/opt/anaconda3/lib/python3.9/site-packages/django/urls/resolvers.py", line 494, in check
    for pattern in self.url_patterns:
  File "/Users/harshithansraj/opt/anaconda3/lib/python3.9/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/harshithansraj/opt/anaconda3/lib/python3.9/site-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Users/harshithansraj/opt/anaconda3/lib/python3.9/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/harshithansraj/opt/anaconda3/lib/python3.9/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
  File "/Users/harshithansraj/opt/anaconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/harshithansraj/Desktop/IT project/django-setup/demo/demo/urls.py", line 22, in <module>
    path("",include("myapp.urls"))
  File "/Users/harshithansraj/opt/anaconda3/lib/python3.9/site-packages/django/urls/conf.py", line 38, in include
    urlconf_module = import_module(urlconf_module)
  File "/Users/harshithansraj/opt/anaconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/harshithansraj/Desktop/IT project/django-setup/demo/myapp/urls.py", line 2, in <module>
    from . import views
  File "/Users/harshithansraj/Desktop/IT project/django-setup/demo/myapp/views.py", line 8
    return render(request,"todos.html",{"todos":})
                                                ^
SyntaxError: invalid syntax
/Users/harshithansraj/Desktop/IT project/django-setup/demo/myapp/views.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
March 21, 2024 - 14:32:23
Django version 4.2.10, using settings 'demo.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.

/Users/harshithansraj/Desktop/IT project/django-setup/demo/myapp/urls.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/Users/harshithansraj/opt/anaconda3/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/Users/harshithansraj/opt/anaconda3/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/harshithansraj/opt/anaconda3/lib/python3.9/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/Users/harshithansraj/opt/anaconda3/lib/python3.9/site-packages/django/core/management/commands/runserver.py", line 133, in inner_run
    self.check(display_num_errors=True)
  File "/Users/harshithansraj/opt/anaconda3/lib/python3.9/site-packages/django/core/management/base.py", line 485, in check
    all_issues = checks.run_checks(
  File "/Users/harshithansraj/opt/anaconda3/lib/python3.9/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/Users/harshithansraj/opt/anaconda3/lib/python3.9/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/Users/harshithansraj/opt/anaconda3/lib/python3.9/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    return check_method()
  File "/Users/harshithansraj/opt/anaconda3/lib/python3.9/site-packages/django/urls/resolvers.py", line 494, in check
    for pattern in self.url_patterns:
  File "/Users/harshithansraj/opt/anaconda3/lib/python3.9/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/harshithansraj/opt/anaconda3/lib/python3.9/site-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Users/harshithansraj/opt/anaconda3/lib/python3.9/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/harshithansraj/opt/anaconda3/lib/python3.9/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
  File "/Users/harshithansraj/opt/anaconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/harshithansraj/Desktop/IT project/django-setup/demo/demo/urls.py", line 22, in <module>
    path("",include("myapp.urls"))
  File "/Users/harshithansraj/opt/anaconda3/lib/python3.9/site-packages/django/urls/conf.py", line 38, in include
    urlconf_module = import_module(urlconf_module)
  File "/Users/harshithansraj/opt/anaconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/harshithansraj/Desktop/IT project/django-setup/demo/myapp/urls.py", line 5
    path("todos/",views.todos,name="Todos")
    ^
SyntaxError: invalid syntax
/Users/harshithansraj/Desktop/IT project/django-setup/demo/myapp/urls.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
March 21, 2024 - 14:34:58
Django version 4.2.10, using settings 'demo.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.

[21/Mar/2024 14:35:00] "GET /todos HTTP/1.1" 301 0
[21/Mar/2024 14:35:00] "GET /todos/ HTTP/1.1" 200 1410
^C%                                                                                                                                                                     
(base) harshithansraj@Harshits-MacBook-Air demo % python manage.py createsuperuser
Username (leave blank to use 'harshithansraj'): 
Email address: 
Password: 
Password (again): 
This password is too short. It must contain at least 8 characters.
This password is too common.
Bypass password validation and create user anyway? [y/N]: N
Password: 
Password (again): 
Superuser created successfully.
(base) harshithansraj@Harshits-MacBook-Air demo % python manage.py runserver
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
March 21, 2024 - 14:36:43
Django version 4.2.10, using settings 'demo.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.

[21/Mar/2024 14:36:48] "GET /todos/ HTTP/1.1" 200 1410
[21/Mar/2024 14:36:51] "GET /admin HTTP/1.1" 301 0
[21/Mar/2024 14:36:51] "GET /admin/ HTTP/1.1" 302 0
[21/Mar/2024 14:36:51] "GET /admin/login/?next=/admin/ HTTP/1.1" 200 4181
[21/Mar/2024 14:36:51] "GET /static/admin/js/theme.js HTTP/1.1" 200 1943
[21/Mar/2024 14:36:51] "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 200 2694
[21/Mar/2024 14:36:51] "GET /static/admin/css/dark_mode.css HTTP/1.1" 200 2929
[21/Mar/2024 14:36:51] "GET /static/admin/css/login.css HTTP/1.1" 200 958
[21/Mar/2024 14:36:51] "GET /static/admin/css/responsive.css HTTP/1.1" 200 18559
[21/Mar/2024 14:36:51] "GET /static/admin/css/base.css HTTP/1.1" 200 21310
[21/Mar/2024 14:36:51] "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 200 3063
[21/Mar/2024 14:37:11] "POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
[21/Mar/2024 14:37:11] "GET /admin/ HTTP/1.1" 200 6217
[21/Mar/2024 14:37:11] "GET /static/admin/css/dashboard.css HTTP/1.1" 200 441
[21/Mar/2024 14:37:11] "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
[21/Mar/2024 14:37:11] "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
[21/Mar/2024 14:37:17] "GET /admin/myapp/todoitem/add/ HTTP/1.1" 200 8758
[21/Mar/2024 14:37:17] "GET /static/admin/css/forms.css HTTP/1.1" 200 9090
[21/Mar/2024 14:37:17] "GET /static/admin/js/actions.js HTTP/1.1" 200 7872
[21/Mar/2024 14:37:17] "GET /static/admin/js/core.js HTTP/1.1" 200 5682
[21/Mar/2024 14:37:17] "GET /static/admin/js/jquery.init.js HTTP/1.1" 200 347
[21/Mar/2024 14:37:17] "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 200 8943
[21/Mar/2024 14:37:17] "GET /static/admin/css/widgets.css HTTP/1.1" 200 11921
[21/Mar/2024 14:37:17] "GET /static/admin/js/prepopulate.js HTTP/1.1" 200 1531
[21/Mar/2024 14:37:17] "GET /static/admin/js/urlify.js HTTP/1.1" 200 7887
[21/Mar/2024 14:37:17] "GET /static/admin/js/prepopulate_init.js HTTP/1.1" 200 586
[21/Mar/2024 14:37:17] "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 200 292458
[21/Mar/2024 14:37:17] "GET /admin/jsi18n/ HTTP/1.1" 200 3343
[21/Mar/2024 14:37:17] "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 200 232381
[21/Mar/2024 14:37:17] "GET /static/admin/js/change_form.js HTTP/1.1" 200 606
[21/Mar/2024 14:37:32] "POST /admin/myapp/todoitem/add/ HTTP/1.1" 302 0
[21/Mar/2024 14:37:32] "GET /admin/myapp/todoitem/ HTTP/1.1" 200 8853
[21/Mar/2024 14:37:32] "GET /static/admin/css/changelists.css HTTP/1.1" 200 6566
[21/Mar/2024 14:37:32] "GET /admin/jsi18n/ HTTP/1.1" 200 3343
[21/Mar/2024 14:37:32] "GET /static/admin/js/filters.js HTTP/1.1" 200 978
[21/Mar/2024 14:37:32] "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 200 331
[21/Mar/2024 14:37:32] "GET /static/admin/img/icon-yes.svg HTTP/1.1" 200 436
[21/Mar/2024 14:37:43] "GET /todos/ HTTP/1.1" 200 1448
^C%           